version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    # If you need to persist any data, uncomment and configure volumes
    # volumes:
    #   - ./data:/app/data
    # If you need to expose any ports, uncomment and configure
    # ports:
    #   - "3000:3000"
